### PR TITLE
Update ArduboyLife.ino

### PR DESCRIPTION
**Pull request by AchillesPDX**
Replaced start() with begin() and not_pressed() with notPressed() to comply with the updated Arduboy library.

### CODE REVIEW

**Comment by shogerr** [comment]
:+1:

**Comment by MLXXXp** [comment]
Thanks @AchillesPDX,

I've just started fixing this after seeing your post on the forum. My local copy has been updated but I had forgotten to push to GitHub.

In addition to the changes you made, all calls to _clearDisplay()_ should be changed to _clear()_.

Only the change from _not_pressed()_ to _notPressed()_ is actually required to prevent compile errors. The other changes just prevent _deprecated function_ warnings. (I'll fix them all, though).

I hope you don't mind but I'm just going to make my own (identical) changes instead of applying this pull request, since I've already got them in my working copy of the repository.

**Comment by AchillesPDX** [comment]
Go nuts! I'm just happy to start getting involved :)

**Comment by MLXXXp** [comment]
Changes incorporated via commit a46655f1b97022eb0b36037f4556f2dc52804bf8.

Thanks again, @AchillesPDX

**Pull request closed without merging**
